repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-added-large-files
    - id: detect-aws-credentials
    - id: fix-encoding-pragma
    - id: check-ast
    - id: check-docstring-first
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      name: docformatter - Format Python docstrings
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.6
  hooks:
    - id: bandit
      name: Bandit - Python common security issues
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      name: Flake8 - Style Guide
      types: [python]
      args:
        - --max-line-length=100
        - --ignore=E722  # bare-except
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.3
  hooks:
    - id: pylint
      name: Pylint - Static code analyzer
